print("***Welcome to the football team name generator***")
city_name = input("Please enter the name of the city you grew up: \n")
pet_name = input("OK. Now, please enter the name of your first pet: \n")+("'s")
print("¡Contratulations!")
band_name = print("Your football team name is ", (pet_name)+" ",city_name)
